# Generated by Django 4.2.18 on 2025-02-01 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_response_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailkey',
            old_name='key',
            new_name='code',
        ),
    ]
