# Generated by Django 4.2.18 on 2025-02-05 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_ads_created_at_response_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='ads.ads'),
        ),
    ]
